version: '3'
services:
  backend:
    build: ./FabSpaceUniandes
    volumes:
      - ./FabSpaceUniandes/:/back # maps host diretory to internal container directory
    working_dir: /back/
    command: sh run.sh
    volumes:
      - ./FabSpaceUniandes/:/back
    depends_on:
      - backend
