version: '3'
services:
  worker:
    env_file:
      - './FabSpaceUniandes/production.env'
    volumes:
      - ./FabSpaceUniandes/:/back # maps host diretory to internal container directory
    working_dir: /back/
    build: ./FabSpaceUniandes
    command: sh runWorker.sh
