version: '3'
services:
  backend:
    env_file:
      - production.env
    build: ./FabSpaceUniandes
    volumes:
      - ./FabSpaceUniandes/:/back # maps host diretory to internal container directory
    working_dir: /back/
    command: sh run.sh
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./FabSpaceUniandesRestApi/:/back
    depends_on:
      - backend
